CREATE TABLE `tbl_cadastrantes` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `CONTRATO` varchar(20) NOT NULL,
 `INSCRIÇÃO` varchar(20) NOT NULL,
 `SEXO` varchar(20) NOT NULL,
 `ESTADO CIVIL` varchar(20) NOT NULL,
 `NOME COMPLETO` varchar(500) NOT NULL,
 `FILIAÇÃO` varchar(500) NOT NULL,
 `CRM` varchar(20) NOT NULL,
 `TELEFONE` varchar(20) NOT NULL,
 `E-MAIL` varchar(200) NOT NULL,
 `DATA DE NASCIMENTO` varchar(10) NOT NULL,
 `RG` varchar(100) NOT NULL,
 `NATURALIDADE` varchar(50) NOT NULL,
 `NACIONALIDADE` varchar(20) NOT NULL,
 `CPF` varchar(20) NOT NULL,
 `TITULO DE ELEITOR` varchar(20) NOT NULL,
 `PIS` varchar(20) NOT NULL,
 `ENDEREÇO` varchar(500) NOT NULL,
 `ENDEREÇO NO NOME` varchar(5) NOT NULL,
 `DADOS BANCARIOS` varchar(500) NOT NULL,
 `FUNÇÃO` varchar(50) NOT NULL,
 `ESPECIALIDADE` varchar(50) NOT NULL,
 `senha` varchar(500) NOT NULL,
 `ID PLANILHA` varchar(50) NOT NULL,
 `EMPRESA` varchar(50) NOT NULL,
 `STATUS` varchar(50) DEFAULT NULL,
 `confirmacao` varchar(100) NOT NULL,
 `submission_date` varchar(100) NOT NULL,
 `ARQUIVO` varchar(5000) NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8