

-- QUANTIDADE DE SOCIOS EFETIVADOS

SELECT COUNT(*) AS qtdesocios FROM `socios`;


-- QUANTIDADE DE CADASTRANTES EM VERIFICAÇAO

SELECT COUNT(*) AS qtdecadastrantes FROM `cadastro`;



-- QUANTIDADE DE USUARIOS CADASTRADOS NO SISTEMA

SELECT COUNT(*) AS qtdeusuarios FROM `tbl_users`;


